import type { SparePart } from '@/lib/types'

export const spareParts: SparePart[] = [
  { id: 'SP-01', reference: 'OIL-1002', name: 'Oil Filter', category: 'Filters', supplier: 'Bosch', quantity: 84, minStock: 20, purchasePrice: 8, sellingPrice: 18, location: 'A1-03', status: 'In Stock' },
  { id: 'SP-02', reference: 'AIR-2204', name: 'Air Filter', category: 'Filters', supplier: 'Mann', quantity: 46, minStock: 15, purchasePrice: 15, sellingPrice: 32, location: 'A1-05', status: 'In Stock' },
  { id: 'SP-03', reference: 'OIL-5030', name: 'Engine Oil 5W-30 (1L)', category: 'Fluids', supplier: 'Castrol', quantity: 210, minStock: 50, purchasePrice: 6, sellingPrice: 12, location: 'B2-01', status: 'In Stock' },
  { id: 'SP-04', reference: 'BRK-3302', name: 'Front Brake Pad Set', category: 'Brakes', supplier: 'Brembo', quantity: 12, minStock: 15, purchasePrice: 62, sellingPrice: 120, location: 'C1-02', status: 'Low Stock' },
  { id: 'SP-05', reference: 'BRK-3410', name: 'Rear Brake Pad Set', category: 'Brakes', supplier: 'Brembo', quantity: 18, minStock: 12, purchasePrice: 54, sellingPrice: 105, location: 'C1-03', status: 'In Stock' },
  { id: 'SP-06', reference: 'IGC-0421', name: 'Ignition Coil', category: 'Electrical', supplier: 'Denso', quantity: 9, minStock: 10, purchasePrice: 40, sellingPrice: 78, location: 'D3-01', status: 'Low Stock' },
  { id: 'SP-07', reference: 'SPK-1180', name: 'Spark Plug Set', category: 'Electrical', supplier: 'NGK', quantity: 34, minStock: 15, purchasePrice: 30, sellingPrice: 64, location: 'D3-04', status: 'In Stock' },
  { id: 'SP-08', reference: 'BAT-7000', name: 'Car Battery 70Ah', category: 'Electrical', supplier: 'Varta', quantity: 6, minStock: 8, purchasePrice: 95, sellingPrice: 165, location: 'D4-01', status: 'Low Stock' },
  { id: 'SP-09', reference: 'MAF-2091', name: 'MAF Sensor', category: 'Sensors', supplier: 'Bosch', quantity: 0, minStock: 5, purchasePrice: 85, sellingPrice: 145, location: 'D2-02', status: 'Out of Stock' },
  { id: 'SP-10', reference: 'THS-2210', name: 'Thermostat', category: 'Cooling', supplier: 'Gates', quantity: 22, minStock: 10, purchasePrice: 20, sellingPrice: 38, location: 'E1-01', status: 'In Stock' },
  { id: 'SP-11', reference: 'WPP-3320', name: 'Water Pump', category: 'Cooling', supplier: 'SKF', quantity: 11, minStock: 6, purchasePrice: 55, sellingPrice: 95, location: 'E1-04', status: 'In Stock' },
  { id: 'SP-12', reference: 'TBK-9001', name: 'Timing Belt Kit', category: 'Engine', supplier: 'Gates', quantity: 7, minStock: 5, purchasePrice: 160, sellingPrice: 280, location: 'F2-01', status: 'In Stock' },
  { id: 'SP-13', reference: 'GSK-1120', name: 'Valve Cover Gasket', category: 'Engine', supplier: 'Elring', quantity: 26, minStock: 10, purchasePrice: 24, sellingPrice: 48, location: 'F2-03', status: 'In Stock' },
  { id: 'SP-14', reference: 'SUS-4401', name: 'Control Arm Bushing', category: 'Suspension', supplier: 'Lemförder', quantity: 30, minStock: 12, purchasePrice: 22, sellingPrice: 45, location: 'G1-02', status: 'In Stock' },
  { id: 'SP-15', reference: 'SUS-8890', name: 'Shock Absorber', category: 'Suspension', supplier: 'Monroe', quantity: 14, minStock: 8, purchasePrice: 70, sellingPrice: 130, location: 'G1-05', status: 'In Stock' },
  { id: 'SP-16', reference: 'AC-5540', name: 'AC Condenser', category: 'Air Conditioning', supplier: 'Valeo', quantity: 5, minStock: 5, purchasePrice: 110, sellingPrice: 190, location: 'H2-01', status: 'Low Stock' },
  { id: 'SP-17', reference: 'FAN-7712', name: 'Cooling Fan Assembly', category: 'Cooling', supplier: 'Valeo', quantity: 8, minStock: 5, purchasePrice: 125, sellingPrice: 210, location: 'E2-02', status: 'In Stock' },
  { id: 'SP-18', reference: 'BCM-6612', name: 'Body Control Module', category: 'Electrical', supplier: 'Continental', quantity: 3, minStock: 4, purchasePrice: 210, sellingPrice: 340, location: 'D4-05', status: 'Low Stock' },
  { id: 'SP-19', reference: 'ATF-4400', name: 'ATF Transmission Fluid (1L)', category: 'Fluids', supplier: 'Castrol', quantity: 96, minStock: 30, purchasePrice: 8, sellingPrice: 14, location: 'B2-04', status: 'In Stock' },
  { id: 'SP-20', reference: 'CLT-2200', name: 'Coolant Antifreeze (1L)', category: 'Fluids', supplier: 'Prestone', quantity: 120, minStock: 40, purchasePrice: 5, sellingPrice: 11, location: 'B2-06', status: 'In Stock' },
  { id: 'SP-21', reference: 'WBL-3301', name: 'Wiper Blade Set', category: 'Accessories', supplier: 'Bosch', quantity: 52, minStock: 20, purchasePrice: 12, sellingPrice: 26, location: 'A3-01', status: 'In Stock' },
  { id: 'SP-22', reference: 'CBF-1102', name: 'Cabin Air Filter', category: 'Filters', supplier: 'Mann', quantity: 38, minStock: 15, purchasePrice: 11, sellingPrice: 24, location: 'A1-07', status: 'In Stock' },
  { id: 'SP-23', reference: 'FUL-6620', name: 'Fuel Filter', category: 'Filters', supplier: 'Bosch', quantity: 9, minStock: 10, purchasePrice: 18, sellingPrice: 36, location: 'A1-09', status: 'Low Stock' },
  { id: 'SP-24', reference: 'CLU-8801', name: 'Clutch Kit', category: 'Transmission', supplier: 'LuK', quantity: 4, minStock: 3, purchasePrice: 240, sellingPrice: 420, location: 'F3-01', status: 'In Stock' },
  { id: 'SP-25', reference: 'ALT-5510', name: 'Alternator', category: 'Electrical', supplier: 'Bosch', quantity: 0, minStock: 4, purchasePrice: 160, sellingPrice: 290, location: 'D4-07', status: 'Out of Stock' },
  { id: 'SP-26', reference: 'STR-9920', name: 'Starter Motor', category: 'Electrical', supplier: 'Valeo', quantity: 6, minStock: 4, purchasePrice: 130, sellingPrice: 235, location: 'D4-09', status: 'In Stock' },
  { id: 'SP-27', reference: 'TIR-2050', name: 'Tire 205/55 R16', category: 'Tires', supplier: 'Michelin', quantity: 40, minStock: 16, purchasePrice: 65, sellingPrice: 115, location: 'J1-01', status: 'In Stock' },
  { id: 'SP-28', reference: 'TIR-2255', name: 'Tire 225/45 R17', category: 'Tires', supplier: 'Continental', quantity: 13, minStock: 16, purchasePrice: 78, sellingPrice: 140, location: 'J1-03', status: 'Low Stock' },
  { id: 'SP-29', reference: 'BLB-1150', name: 'Headlight Bulb H7', category: 'Accessories', supplier: 'Osram', quantity: 88, minStock: 30, purchasePrice: 4, sellingPrice: 12, location: 'A3-05', status: 'In Stock' },
  { id: 'SP-30', reference: 'SNS-3380', name: 'Oxygen Sensor', category: 'Sensors', supplier: 'NGK', quantity: 15, minStock: 8, purchasePrice: 48, sellingPrice: 92, location: 'D2-06', status: 'In Stock' },
]
